### PR TITLE
Fixes for compiling on Linux

### PR DESCRIPTION
**Pull request by johncheetham**
Fix the Linux build. Type 'make' in the top level directory to build it.
There are some issues running it, most noticeable the fact that there are no dark squares on the board.
I was able to add the stockfish engine ok though and play some moves against it.

### CODE REVIEW

**Comment by billforsternz** [comment]
Thanks you very much for this effort. Unfortunately I am travelling for two
weeks. I will be very keen to merge this as soon as possible after I return
home.
Bill.

**Comment by johncheetham** [comment]
I added a change to ChessBoardBitmap.cpp so the dark board squares are displayed correctly.

**Comment by billforsternz** [comment]
I reproduced your Linux build today on ubuntu 16.04 LTS. It works pretty well, great job! On a vanilla ubuntu system I only needed to perform the following prerequisites before following your instructions;

sudo apt install libwxgtk3.0-dev
sudo apt install libwxgtk-media3.0-dev
sudo apt install libwxgtk-webview3.0-dev

I also added
src := $(filter-out tabartmsw.cpp, $(src))

to src/Makefile because tabartmsw.cpp is a modified replacement component of the MS Windows version of the aui library. It solves an obscure problem I had in Windows 10 but not other Windows flavours - totally irrelevant to a Linux build.

I have run out of time for now. Tomorrow I will do the git formalities - I don't want to rush them because the merge commands are not familiar territory.

The most obvious problem I see is that the text representation pane is not updating properly,

Thanks again.

**Comment by billforsternz** [comment]
I followed the manual command line merge process provided by Github.com. Presumably I should now close the pull request, but I will leave it open for a day or two in case John Cheetham wishes to comment.

**Comment by johncheetham** [comment]
I think the pull request is closed automatically when you do the merge. I think I can still comment though.

I don't have a problem with the text representation pane when using wxwidgets 3.1.0 (compiled from source) on Debian 9. When I use the Debian package (version 3.0.2) though I get the problem you describe.

I skipped the SetIcon command to get it to compile. From the compiler error it looks like a bbbbbbbb_xpm file needs setting up.

Hopefully I will get a chance to look at these issues and do a bit more Linux testing.

**Comment by johncheetham** [comment]
I removed the freeze/thaw from GameView::Display and it seemed to fix the text pane update issue.

**Comment by billforsternz** [comment]
I tried out the freeze/thaw thing and enjoyed the results immensely. It looks like an issue I had discovered when experimenting on Mac, so I just changed THC_MAC to THC_UNIX. I also updated README.md to reflect these recent developments and your contribution. Thanks again.

I'm putting aside the much less important icon issue as I have a busy few days ahead. I remember there are some hacks and weirdness in that area, but my feeling is they are Windows specific. Maybe it's as simple as me not adding the .xpm file to the repository or something. I'll come back to this later.

**Pull request merged**
